### ISSUE TITLE
Error when used as dependency in React 17

### ISSUE THREAD

**Issue by mariovde-IIO** [vchirkov/webgl-stuff#2]
Hi all,
I can't seem to get the dependency to work in React.

Currently:
node: v14.15.0
yarn: yarn2
React: v17

Error
webgl_stuff__WEBPACK_IMPORTED_MODULE_1___default(...) is not a constructor

Code
const wgs = new WebglStuff(canvas.current);
wgs.transitTo(WebglStuff.presets.progress.normal, 5000);

any help on this would be very appreciated!

**Comment by vchirkov** [comment]
Hi Mate!

Thanks for the details in the issue. Indeed, the lib had compilation issues when used with CRA or similar.
I've updated it to be compiled with Rollup, seems like it resolved the problem.

Please, check out version 1.4.0, you should be fine.

Let me know if you encounter any other issues.
